name: push-deploy-world

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  push-or-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/deploy-with-version.yml
        with:
          dcl-sdk-package: '@dcl/sdk/next'
          bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}