name: push-deploy-world

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  push-or-pr:
    uses: ./.github/workflows/deploy-with-version.yml
      with:
        dcl-sdk-package: '@dcl/sdk@next'
      secrets:
        bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}